# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-01 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180801_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='comment',
        ),
    ]
