# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-29 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post',
            field=models.CharField(default='DEFAULT VALUE', max_length=500),
        ),
    ]
