# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-29 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated',
        ),
    ]
